### ISSUE TITLE
SMB Shares not working on v18.0.4

### ISSUE THREAD

**Issue by waja** [hoellen/dockerfiles#38] opened 2020-05-13 12:37 UTC
Hi there,

your lastest nextcloud 18 image is affected by https://github.com/nextcloud/server/issues/20622.

Any chance to work around this issue until nextcloud fixes this?

Thanks, Jan.

**Comment by hoellen** [comment] 2020-05-14 07:34
I created a branch [smb-fix](https://github.com/hoellen/dockerfiles/tree/smb-fix) with the patch from https://github.com/nextcloud/server/pull/20941. You can test it with the image tag `hoellen/nextcloud:18.0-smb`. 

If it is working for you, I can push it on the stable `18.0` tag.

**Comment by waja** [comment] 2020-05-15 07:33
@hoellen great, this seems to work quite nice. many thanks!

**Comment by wiswedel** [comment] 2020-05-22 06:41
duplicate of https://github.com/nextcloud/server/issues/20622
fixed by https://github.com/nextcloud/server/pull/20941

**Comment by hoellen** [comment] 2020-06-09 15:20
Fixed by 18.0.5 and later

**Closed as completed by hoellen** 2020-06-09 15:20 UTC
