### ISSUE TITLE
Nextcloud 20 occ stuck

### ISSUE THREAD

**Issue by lexxxel** [hoellen/dockerfiles#44] opened 2020-10-05 22:27 UTC
I can't upgrade from nextcloud 19.0 to 20.0 . 
The run.sh is always stuck with occ upgrade. When I step into the container with `docker exec -it nextcloud sh`, I can't run occ, even without parameters. The script is just stuck.

**Comment by waja** [comment] 2020-10-06 04:31
Hi,

> The run.sh is always stuck with occ upgrade. When I step into the container with docker exec -it nextcloud sh, I can't run occ, even without parameters. The script is just stuck.

I can confirm this, even for a new setup.

Cheers, Jan.

**Comment by hoellen** [comment] 2020-10-06 07:34
Sorry, I've already submitted a patch [upstream](https://github.com/nextcloud/server/pull/23158).
I try to find some time in the evening to apply it to the docker image. 
For now, you can safely downgrade to 19.0 because occ gets stuck before the upgrade.

**Comment by lexxxel** [comment] 2020-10-06 07:48
Unlucky me can't downgrade :innocent: ... I `sh` into the container, killed the process, triggered the update from the website and ended with a 'working 20.0', only that the cron job get's stuck and boosts my cpu clock while occupying 1 full core :see_no_evil:.
I will happily wait for your fix 👍  

PS: I read your PR ... and see how it reflects with my experience ❤️

**Comment by waja** [comment] 2020-10-06 08:08
> For now, you can safely downgrade to 19.0 because occ gets stuck before the upgrade.

If you not killed the PHP process inside the container and not upgraded the instance to 20.0, because you only stoped the container, this should work. At least it worked well for me.

**Comment by hoellen** [comment] 2020-10-06 11:49
Okay. I've downgraded the image to PHP 7.3. That will be faster and fixes it, also. 
Then we wait until the bugfix is released upstream and go back to PHP 7.4.

**Comment by zerpex** [comment] 2021-01-03 10:53
Hi,

Is it possible to either upgrade to php 7.4 or give the choice of php version used ?
I am using the password app and the last update require php 7.4 !

Regards,
zer

**Comment by hoellen** [comment] 2021-01-03 13:16
Fix is included in the upstream release and there is also an UID check on start now.
So we can use the PHP 7.4 as base image for Nextcloud 20 again (see commit https://github.com/hoellen/dockerfiles/commit/b60120888d0d340f4f88fb2a3cf711dc732748af and https://github.com/hoellen/dockerfiles/commit/ed47c8a632451a3832a6b489198f615d607df8d5).

**Closed as completed by hoellen** 2021-01-03 13:16 UTC
